{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "history_visible": true,
      "authorship_tag": "ABX9TyMx1t+k7lsjI1ccufnPjhj6",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Profex04/Connect4/blob/main/CSCE_Connect4.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "3vxE-omskE8d"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "\n",
        "class Board():\n",
        "    def __init__(self):\n",
        "        self.N_OF_ROWS = 6;\n",
        "        self.N_OF_COLS = 7;\n",
        "        self.stones = ['O', 'X'];\n",
        "        self.boardMatrix = np.empty((self.N_OF_ROWS,self.N_OF_COLS), dtype='<U1');\n",
        "        for i in range(self.N_OF_ROWS):\n",
        "            for j in range(self.N_OF_COLS):\n",
        "                self.boardMatrix[i][j] = '_';\n",
        "\n",
        "    def getBoard(self):\n",
        "        return self.boardMatrix;\n",
        "\n",
        "    def setStone(self, move, playerNo):\n",
        "        self.boardMatrix[move.row][move.col] = self.stones[playerNo%2];\n",
        "\n",
        "    def copyBoard(self, copyFromBoard):\n",
        "        for i in range(self.N_OF_ROWS):\n",
        "            for j in range(self.N_OF_COLS):\n",
        "                self.boardMatrix[i][j] = copyFromBoard[i][j];\n",
        "\n",
        "    def printBoard(self):\n",
        "        print(\" 0123456\");\n",
        "        for i in range(self.N_OF_ROWS):\n",
        "            print(i,end='');\n",
        "            for j in range(self.N_OF_COLS):\n",
        "                print(self.boardMatrix[i][j],end='');\n",
        "            print(\"\\n\");\n",
        "\n",
        "class Move:\n",
        "    def __init__(self, row, col):\n",
        "        self.row = row;\n",
        "        self.col = col;\n",
        "\n",
        "class Player:\n",
        "    def __init__(self, isComputer, board, game):\n",
        "        self.isWinner = False;\n",
        "        self.isComputer = isComputer;\n",
        "        self.board = board;\n",
        "        self.game = game;\n",
        "\n",
        "    def getMove(self, isComputer, board, game, level, predictions):\n",
        "        if isComputer == False:\n",
        "            #print(\"Please enter your move [row, column]\");\n",
        "            row = predictions.row;\n",
        "            col = predictions.col;\n",
        "            move = Move(row, col);\n",
        "            return move;\n",
        "        else:\n",
        "            #BOT VS BOT HARD STRATEGY WILL PLAY AGAINST RANDOM\n",
        "            if level == 0 or (game.computerVsComputer and game.activePlayer == 1):\n",
        "                return self.strategyEasy(game);\n",
        "            else:\n",
        "                #return self.strategyHard(board, game);\n",
        "                return self.strategyHardFutureLookAheadRecursive(board, game, Move(-1, -1), 1, game.legalMoves)\n",
        "\n",
        "    def strategyEasy(self, game):\n",
        "        while True:\n",
        "            selection = np.random.randint(len(game.legalMoves)); #there is always 6 moves available until end game\n",
        "            if not (game.legalMoves[selection].row == -1):\n",
        "                break\n",
        "        return game.legalMoves[selection];\n",
        "\n",
        "    def strategyHard(self, board, game):\n",
        "        for windowLen in range(4, 1):\n",
        "            if move.row != -1: #n/a spot\n",
        "                for move in game.legalMoves:\n",
        "                    if game.checkHorizontal(board, move, windowLen, True) or game.checkVertical(board, move, windowLen, True) or game.checkDiagonal(board, move, windowLen, True, False) or game.checkDiagonal(board, move, windowLen, True, True):\n",
        "                        return move;\n",
        "        return self.strategyEasy(game); #cannot find good move\n",
        "\n",
        "    def strategyHardFutureLookAheadRecursive(self, board, game, prevMove, lookAhead, legalMoves):\n",
        "        copyBoard = Board()\n",
        "        copyBoard.copyBoard(board.getBoard());\n",
        "        copyLegalMoves = np.empty(board.N_OF_COLS, dtype=Move)\n",
        "        i = 0\n",
        "        for move in legalMoves:\n",
        "            copyLegalMoves[i] = move;\n",
        "            i += 1\n",
        "\n",
        "        lookAhead += 1; #counter for stopping after looking ahead 3 moves (3 is hardcoded as seen below)\n",
        "\n",
        "        for windowLen in range(4, 1, -1):\n",
        "            for counterMove in copyLegalMoves:\n",
        "                if counterMove.row != -1 and not(counterMove.row == prevMove.row and counterMove.col == prevMove.col): # n/a spot\n",
        "                    if(game.checkHorizontal(copyBoard, counterMove, windowLen, True) or game.checkVertical(copyBoard, counterMove, windowLen, True) or game.checkDiagonal(copyBoard, counterMove, windowLen, True, False) or game.checkDiagonal(copyBoard, counterMove, windowLen, True, True)):\n",
        "                        if(lookAhead == 3):\n",
        "                            return prevMove;\n",
        "\n",
        "                        #Sets the stone and updates legal moves left on 'pretend' copies of board matrix and legal moves list\n",
        "                        copyBoard.setStone(counterMove, (game.activePlayer+1)%2);\n",
        "                        if(counterMove.row != 0):\n",
        "                            copyLegalMoves[counterMove.col] = Move(counterMove.row-1, counterMove.col);\n",
        "                        else:\n",
        "                            copyLegalMoves[counterMove.col] = Move(-1, -1);\n",
        "\n",
        "                        return self.strategyHardFutureLookAheadRecursive(copyBoard, game, counterMove, lookAhead, copyLegalMoves);\n",
        "        if(prevMove.row != -1 and prevMove.col != -1):\n",
        "            return prevMove; #recursive func starts with dummy previous move (-1, -1)\n",
        "        else:\n",
        "            return self.strategyEasy(game); #cannot find good move\n",
        "\n",
        "class Game():\n",
        "    def __init__(self, p2p, computerVsComputer, level):\n",
        "        self.board = Board();\n",
        "        self.p2p = p2p;\n",
        "        self.level = level;\n",
        "        self.winner = -1;\n",
        "        self.gameOver = False;\n",
        "        self.activePlayer = 0;\n",
        "        self.computerVsComputer = computerVsComputer\n",
        "        self.players = np.empty(2, dtype=Player)\n",
        "        if not computerVsComputer:\n",
        "            self.players[0] = Player(False, self.board, self);\n",
        "            isComputer = False if p2p else True;\n",
        "            self.players[1] = Player(isComputer, self.board, self);\n",
        "        else:\n",
        "            self.players[0] = Player(True, self.board, self)\n",
        "            self.players[1] = Player(True, self.board, self)\n",
        "        self.legalMoves = np.empty(self.board.N_OF_COLS)\n",
        "        self.legalMoves = [Move(5,0), Move(5,1), Move(5,2), Move(5,3), Move(5,4), Move(5,5), Move(5,6)];\n",
        "        #self.runGameLoop();\n",
        "        self.playerOneWins = False;\n",
        "        self.playerTwoWins = False;\n",
        "\n",
        "    def getWinner(self):\n",
        "        return self.winner;\n",
        "\n",
        "    def getActivePlayer(self):\n",
        "        return self.activePlayer;\n",
        "\n",
        "    def setLevel(self, level):\n",
        "        self.level = level;\n",
        "\n",
        "    def setP2P(self, p2p):\n",
        "        self.p2p = p2p;\n",
        "\n",
        "    def getGameOver(self):\n",
        "        return self.gameOver;\n",
        "\n",
        "    def gameTurn(self, activePlayer, predictions):\n",
        "        isComputer = False if ((self.p2p or activePlayer % 2 == 0) and not self.computerVsComputer) else True\n",
        "        move = self.players[activePlayer].getMove(isComputer, self.board, self, self.level, predictions)\n",
        "        while not self.checkLegalMove(self.board, move, activePlayer):\n",
        "            move = self.players[activePlayer].getMove(isComputer, self.board, self, self.level, predictions)\n",
        "        self.board.setStone(move, activePlayer)\n",
        "        if move.row != 0:\n",
        "            self.legalMoves[move.col] = Move(move.row - 1, move.col)\n",
        "        else:\n",
        "            self.legalMoves[move.col] = Move(-1, -1)  # spot not available anymore\n",
        "        return move\n",
        "\n",
        "\n",
        "    def checkHorizontal(self, board, move, windowLen, testFlag):\n",
        "        horizontalCheck = False;\n",
        "        row = move.row; #only check the row of the last move\n",
        "        for j in range(max(0, move.col-(windowLen)), min(move.col+1, board.N_OF_COLS-windowLen+1)):\n",
        "            if j+windowLen <= board.N_OF_COLS:\n",
        "                consecutiveStones = board.getBoard()[row, j:j+windowLen]\n",
        "                if len(consecutiveStones) == windowLen:\n",
        "                    horizontalCheck = self.checkIfConnected(consecutiveStones, windowLen, testFlag);\n",
        "                if horizontalCheck == True:\n",
        "                    return horizontalCheck;\n",
        "        return horizontalCheck;\n",
        "\n",
        "    def checkVertical(self, board, move, windowLen, testFlag):\n",
        "        verticalCheck = False;\n",
        "        col = move.col; #only check the col of the last move\n",
        "        for i in range(max(0, move.row-(windowLen)), min(move.row+1, board.N_OF_ROWS-windowLen+1)):\n",
        "            consecutiveStones = board.getBoard()[i:i+windowLen, col]\n",
        "            if len(consecutiveStones) == windowLen:\n",
        "                verticalCheck = self.checkIfConnected(consecutiveStones, windowLen, testFlag);\n",
        "            if verticalCheck == True:\n",
        "                return verticalCheck;\n",
        "            consecutiveStones = [];\n",
        "        return verticalCheck;\n",
        "\n",
        "    def checkDiagonal(self, board, move, windowLen, testFlag, reverseFlag):\n",
        "        diagonalCheck = False\n",
        "        consecutiveStones = []\n",
        "\n",
        "        if abs(move.row-move.col) <= 3 and not reverseFlag:\n",
        "            for i, j in zip(range(max(0, move.row - (windowLen - 1)), min(move.row, board.N_OF_ROWS - windowLen) + 1), range(max(0, move.col - (windowLen - 1)), min(move.col, board.N_OF_COLS - windowLen) + 1)):\n",
        "                for k in range(windowLen):\n",
        "                    consecutiveStones.append(board.getBoard()[i + k][j + k])\n",
        "                    if i + k + 1 >= board.N_OF_ROWS or j + k + 1 >= board.N_OF_COLS:\n",
        "                        break\n",
        "                if len(consecutiveStones) == windowLen:\n",
        "                     diagonalCheck = self.checkIfConnected(consecutiveStones, windowLen, testFlag)\n",
        "                if diagonalCheck:\n",
        "                     return diagonalCheck\n",
        "                consecutiveStones = []\n",
        "\n",
        "        if move.row + move.col <= 8 and move.row + move.col > 2 and reverseFlag:\n",
        "            i_start = max(0, move.row - (windowLen - 1))\n",
        "            j_start = min(move.col + (move.row - i_start), board.N_OF_COLS)\n",
        "            for i, j in zip(range(i_start, min(move.row, board.N_OF_ROWS - windowLen) + 1), range(j_start, move.col + 1)):\n",
        "                for k in range(windowLen):\n",
        "                    consecutiveStones.append(board.getBoard()[i + k][j - k])\n",
        "                    if i + k + 1 >= board.N_OF_ROWS or j - k - 1 < 0:\n",
        "                        break\n",
        "                if len(consecutiveStones) == windowLen:\n",
        "                    diagonalCheck = self.checkIfConnected(consecutiveStones, windowLen, testFlag)\n",
        "                if diagonalCheck:\n",
        "                    return diagonalCheck\n",
        "                consecutiveStones = []\n",
        "        return diagonalCheck;\n",
        "\n",
        "    def checkLegalMove(self, board, move, activePlayer):\n",
        "        while move.row < board.N_OF_ROWS - 1 and board.getBoard()[move.row + 1][move.col] == '_':\n",
        "            move.row += 1\n",
        "\n",
        "        if board.getBoard()[move.row][move.col] != '_' or move.col >= board.N_OF_COLS:\n",
        "            return False\n",
        "        return True\n",
        "\n",
        "    def checkIfConnected(self, consecutiveStones, windowLen, testFlag):\n",
        "        left = 0\n",
        "        sum = 0\n",
        "        prevSum = 0\n",
        "        while left < windowLen and not (np.abs(sum) < np.abs(prevSum)):\n",
        "            prevSum = sum\n",
        "            if consecutiveStones[left] == 'X':\n",
        "                sum += 1\n",
        "            elif consecutiveStones[left] == 'O':\n",
        "                sum -= 1\n",
        "            left += 1\n",
        "\n",
        "        if testFlag:\n",
        "            blanks = 0\n",
        "            for elem in consecutiveStones:\n",
        "                if elem == '_':\n",
        "                    blanks += 1\n",
        "            if blanks == 1 and (sum == windowLen - 1 or sum == -1 * (windowLen - 1)):\n",
        "                return True\n",
        "\n",
        "        if sum == windowLen or sum == -1 * windowLen:\n",
        "            return True\n",
        "        else:\n",
        "            return False\n",
        "\n",
        "    def checkIfWin(self, move):\n",
        "        if self.checkHorizontal(self.board, move, 4, False) == True:\n",
        "            self.winner = self.activePlayer;\n",
        "            self.gameOver = True;\n",
        "        elif self.checkVertical(self.board, move, 4, False) == True:\n",
        "            self.winner = self.activePlayer;\n",
        "            self.gameOver = True;\n",
        "        elif self.checkDiagonal(self.board, move, 4, False, False) == True:\n",
        "            self.winner = self.activePlayer;\n",
        "            self.gameOver = True;\n",
        "        elif self.checkDiagonal(self.board, move, 4, False, True) == True:\n",
        "            self.winner = self.activePlayer;\n",
        "            self.gameOver = True;\n",
        "        self.playerOneWins = self.gameOver and self.activePlayer==0;\n",
        "        self.playerTwoWins = self.gameOver and self.activePlayer==1;\n",
        "        return self.gameOver;\n",
        "\n",
        "class Environment:\n",
        "    def __init__(self, computerVsComputer, level):\n",
        "        self.game = Game(False, computerVsComputer, level); #p2p flag=false, 1=hard level 0=easy level\n",
        "        self.actionSpace = np.arange(len(self.game.legalMoves))\n",
        "        self.observationSpace = self.encode(self.game.board.boardMatrix)\n",
        "        self.computerVsComputer = computerVsComputer\n",
        "        self.level = level\n",
        "\n",
        "    def encode(self, stateMatrix):\n",
        "        return tuple(tuple(row) for row in stateMatrix)\n",
        "\n",
        "    def reset(self):\n",
        "        self.game = Game(False, self.computerVsComputer, self.level);\n",
        "        self.observationSpace = self.encode(self.game.board.boardMatrix)\n",
        "        state = self.observationSpace\n",
        "        return state\n",
        "\n",
        "    def step(self, action):\n",
        "        move = self.game.gameTurn(self.game.activePlayer, action);\n",
        "        self.game.checkIfWin(move)\n",
        "        self.observationSpace = self.encode(self.game.board.boardMatrix)\n",
        "        if self.game.playerOneWins:\n",
        "            reward = 20\n",
        "        elif self.game.playerTwoWins:\n",
        "            reward = -10\n",
        "        else:\n",
        "            reward = -1\n",
        "        done = self.game.gameOver\n",
        "        self.game.activePlayer = (self.game.activePlayer+1) % 2;\n",
        "        return (self.observationSpace, reward, done)\n",
        "\n",
        "    def sample(self):\n",
        "        while True:\n",
        "            selection = np.random.randint(len(self.game.legalMoves)); #there is always 6 moves available until end game\n",
        "            if not (self.game.legalMoves[selection].row == -1):\n",
        "                break\n",
        "        #return [self.game.legalMoves[selection].row, self.game.legalMoves[selection].col];\n",
        "        return selection\n",
        "\n",
        "    def render(self):\n",
        "        #self.game.board.printBoard();\n",
        "        renderedObservationSpace = np.empty((self.game.board.N_OF_ROWS, self.game.board.N_OF_COLS), dtype='<U1')\n",
        "        for row in range(np.shape(self.observationSpace)[0]):\n",
        "            for col in range(np.shape(self.observationSpace)[1]):\n",
        "                renderedObservationSpace[row][col] = self.observationSpace[row][col]\n",
        "        return renderedObservationSpace\n",
        "\n",
        "#game = Game(False, 1); #p2p flag=false, 1=hard level 0=easy level\n",
        "\n",
        "from IPython.display import clear_output\n",
        "from time import sleep\n",
        "def print_frames(frames):\n",
        "    for i, frame in enumerate(frames):\n",
        "        clear_output(wait=True)\n",
        "        print(frame['frame'])\n",
        "        print(f\"Timestep: {i + 1}\")\n",
        "        print(f\"State: {frame['state']}\")\n",
        "        print(f\"Action: {frame['action']}\")\n",
        "        print(f\"Reward: {frame['reward']}\")\n",
        "        sleep(.15)\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "#BOT VS BOT (WITHOUT REINFORCEMENT LEARNING)\n",
        "env = Environment(True, 1) #computerVsComputer flag=True, level=hard for Player 1, easy for Player 2\n",
        "total_epochs, total_won = 0, 0\n",
        "episodes = 100\n",
        "for i in range(1, episodes):\n",
        "    state = env.reset()\n",
        "\n",
        "    done = False\n",
        "    won = 0\n",
        "    epochs = 0\n",
        "    reward = 0\n",
        "    frames = [] # for animation\n",
        "    while not done:\n",
        "        no_moves_left = all(move.row == -1 for move in env.game.legalMoves)\n",
        "        if(no_moves_left): break\n",
        "\n",
        "        actionIndex = env.sample()\n",
        "        action = env.game.legalMoves[actionIndex]\n",
        "        state, reward, done = env.step(action)\n",
        "        frames.append({\n",
        "            'frame': env.render(),\n",
        "            'state': state,\n",
        "            'action': (action.row, action.col),\n",
        "            'reward': reward\n",
        "            })\n",
        "        epochs += 1\n",
        "        if reward == 20:\n",
        "            won = 1\n",
        "        else:\n",
        "            won = 0\n",
        "    print(\"Timesteps taken: {}\".format(epochs))\n",
        "    print_frames(frames)\n",
        "    total_epochs += epochs\n",
        "    total_won += won\n",
        "\n",
        "print(f\"Results after {episodes} episodes:\")\n",
        "print(f\"Average timesteps per episode: {total_epochs / episodes}\")\n",
        "print(f\"Number of times won: {total_won / episodes}\")\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Mkysoup8gMFE",
        "outputId": "ede33fc1-6eeb-49aa-b7e5-a57a552e322b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[['X' '_' '_' '_' '_' '_' '_']\n",
            " ['X' '_' '_' '_' '_' '_' '_']\n",
            " ['O' '_' '_' '_' '_' '_' '_']\n",
            " ['X' 'O' 'O' '_' '_' '_' '_']\n",
            " ['O' 'X' 'X' 'O' 'X' '_' '_']\n",
            " ['O' 'O' 'X' 'O' 'O' 'X' 'X']]\n",
            "Timestep: 18\n",
            "State: (('X', '_', '_', '_', '_', '_', '_'), ('X', '_', '_', '_', '_', '_', '_'), ('O', '_', '_', '_', '_', '_', '_'), ('X', 'O', 'O', '_', '_', '_', '_'), ('O', 'X', 'X', 'O', 'X', '_', '_'), ('O', 'O', 'X', 'O', 'O', 'X', 'X'))\n",
            "Action: (4, 4)\n",
            "Reward: -1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import time\n",
        "#IMPLEMENTING Q LEARNING\n",
        "env = Environment(False, 0) #during training, player 1 will be AI, player 2 will be computer bot (hard strategy)\n",
        "q_table = {} #although there are possible 3^42 possible states theoretically, due to game rules this q table will be much much smaller and dynamically managed\n",
        "\n",
        "start_time = time.time()\n",
        "\n",
        "#Hyperparameters\n",
        "alpha = 0.1\n",
        "gamma = 0.6\n",
        "epsilon = 0.1\n",
        "\n",
        "# For plotting metrics\n",
        "all_epochs = []\n",
        "\n",
        "for i in range(1, 100001):\n",
        "    state = env.reset()\n",
        "\n",
        "    epochs, penalty, reward, = 0, 0, 0\n",
        "    #frames = [] # for animation\n",
        "    done = False\n",
        "\n",
        "    while not done:\n",
        "\n",
        "        no_moves_left = all(move.row == -1 for move in env.game.legalMoves)\n",
        "        if(no_moves_left): break\n",
        "\n",
        "        if state not in q_table:\n",
        "            q_table[state] = np.zeros(len(env.actionSpace))\n",
        "\n",
        "        if np.random.uniform(0, 1) < epsilon:\n",
        "            actionIndex = env.sample() # Explore action space\n",
        "        else:\n",
        "            actionIndex = np.argmax(q_table[state]) # Exploit learned values\n",
        "            if (env.game.legalMoves[actionIndex].row == -1):\n",
        "                penalty = -1 #penalty for choosing a non-legal move\n",
        "                actionIndex = env.sample()\n",
        "            else:\n",
        "                penalty = 0\n",
        "\n",
        "        action = env.game.legalMoves[actionIndex]\n",
        "        next_state, reward, done = env.step(action)\n",
        "        reward += penalty\n",
        "\n",
        "        if next_state not in q_table:\n",
        "            q_table[next_state] = np.zeros(len(env.actionSpace))\n",
        "\n",
        "        old_value = q_table[state][actionIndex]\n",
        "        next_max = np.max(q_table[next_state])\n",
        "\n",
        "        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)\n",
        "        q_table[state][actionIndex] = new_value\n",
        "\n",
        "        state = next_state\n",
        "        #frames.append({\n",
        "        #'frame': env.render(),\n",
        "        #'state': state,\n",
        "        #'action': (action.row, action.col),\n",
        "        #'reward': reward\n",
        "        #})\n",
        "        epochs += 1\n",
        "        #env.game.board.printBoard()\n",
        "        #clear_output(wait=True)\n",
        "\n",
        "    if i % 100 == 0:\n",
        "        clear_output(wait=True)\n",
        "        print(f\"Episode: {i}\")\n",
        "\n",
        "    #print_frames(frames)\n",
        "\n",
        "print(\"Training finished.\\n\")\n",
        "print(\"--- %s seconds ---\" % (time.time() - start_time))\n"
      ],
      "metadata": {
        "id": "yD-aXmmjgyTA",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "24fb0226-2afb-4cca-a903-fa05ef741f58"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Episode: 100000\n",
            "Training finished.\n",
            "\n",
            "--- 286.27652502059937 seconds ---\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"Evaluate agent's performance after Q-learning\"\"\"\n",
        "\n",
        "total_epochs, total_won = 0, 0\n",
        "episodes = 100\n",
        "env.level = 0 #AI WILL PLAY AGAINST RANDOM PLAYING BOT FOR COMPARISON\n",
        "\n",
        "for episode in range(episodes):\n",
        "    state = env.reset()\n",
        "    epochs, penalty, reward = 0, 0, 0\n",
        "    frames = [] #for animation\n",
        "    done = False\n",
        "\n",
        "    while not done:\n",
        "        no_moves_left = all(move.row == -1 for move in env.game.legalMoves)\n",
        "        if(no_moves_left): break\n",
        "        if state not in q_table:\n",
        "            q_table[state] = np.zeros(len(env.actionSpace))\n",
        "        actionIndex = np.argmax(q_table[state])\n",
        "        if (env.game.legalMoves[actionIndex].row == -1):\n",
        "            actionIndex = env.sample()\n",
        "            penalty = -1\n",
        "        else:\n",
        "            penalty = 0\n",
        "        action = env.game.legalMoves[actionIndex]\n",
        "        state, reward, done = env.step(action)\n",
        "        reward += penalty\n",
        "\n",
        "        if reward == 20:\n",
        "            won = 1\n",
        "        else:\n",
        "            won = 0\n",
        "\n",
        "        frames.append({\n",
        "        'frame': env.render(),\n",
        "        'state': state,\n",
        "        'action': (action.row, action.col),\n",
        "        'reward': reward\n",
        "        })\n",
        "        epochs += 1\n",
        "\n",
        "\n",
        "    total_epochs += epochs\n",
        "    total_won += won\n",
        "    print_frames(frames)\n",
        "\n",
        "print(f\"Results after {episodes} episodes:\")\n",
        "print(f\"Average timesteps per episode: {total_epochs / episodes}\")\n",
        "print(f\"Percentage won: {total_won / episodes}\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "_9Qo-dhJNGvO",
        "outputId": "640d11f6-7dd0-4128-b3a2-3a3cb0719421"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[['_' '_' '_' '_' '_' '_' '_']\n",
            " ['_' '_' '_' '_' '_' '_' '_']\n",
            " ['_' '_' '_' '_' '_' '_' '_']\n",
            " ['_' '_' '_' '_' '_' '_' '_']\n",
            " ['_' '_' '_' 'X' '_' '_' '_']\n",
            " ['O' 'O' 'O' 'O' 'X' '_' 'X']]\n",
            "Timestep: 7\n",
            "State: (('_', '_', '_', '_', '_', '_', '_'), ('_', '_', '_', '_', '_', '_', '_'), ('_', '_', '_', '_', '_', '_', '_'), ('_', '_', '_', '_', '_', '_', '_'), ('_', '_', '_', 'X', '_', '_', '_'), ('O', 'O', 'O', 'O', 'X', '_', 'X'))\n",
            "Action: (5, 0)\n",
            "Reward: 20\n",
            "Results after 100 episodes:\n",
            "Average timesteps per episode: 9.36\n",
            "Percentage won: 0.91\n"
          ]
        }
      ]
    }
  ]
}