[package]
name = "backend2"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
http = "1.3.1"
rand = "0.8"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = {version = "0.6.2", features=["cors"] }

[dependencies.mongodb]
version = "3.2.1"
